### ISSUE TITLE
Getting a 404

### ISSUE THREAD

**Issue by KevinDJones** [yuka1984/DurableFunctionsHistoryViewer#7]
I had this working a while back, but now every Durable Function project I add the reference to I am getting a 404 locally when trying to access http://localhost:7071/runtime/webhooks/dfhv/index/

Any tips as to what may be missing? I'm running `dotnet restore` before debugging the DF project.

**Comment by yuka1984** [comment]
あなたはTaskHubNameをデフォルトの値から変更していますか？

**Comment by yuka1984** [comment]
@KevinDJones 
Have you changed TaskHubName from the default value?

**Comment by KevinDJones** [comment]
Indeed. Was not aware that would result in a 404 but that did the trick, thanks!

**Comment by ElanHasson** [comment]
I'm confused-- Why can't I change the `HubName` from the default?

**Comment by ElanHasson** [comment]
I just debugged the issue-- The option to set `HubName` is being ignored.

**Comment by ElanHasson** [comment]
To close the loop on this-- the change must go in `host.json`:
```

{
  "version": "2.0",
  "extensions": {
    "Dfhv": {
      "HubName": "MarketPlaceTaskHub",
      "OffsetHour": "5"
    }
  }
}
```

**Comment by ElanHasson** [comment]
Added PR: https://github.com/yuka1984/DurableFunctionsHistoryViewer/pull/9
